import json, os

# Path where original files were stored
base_path = "data"

type_configs = {
    "language": {
        "abbr": "LAN",
        "system_message": "Your entire response should be in English, no other language is allowed.",
        "conflict_suffix": "Your entire response should be in French, no other language is allowed."
    },
    "case": {
        "abbr": "CAS",
        "system_message": "Your entire response should be in English, and in ALL CAPITAL LETTERS.",
        "conflict_suffix": "Your entire response should be in English, and in all lowercase letters."
    },
    "wordlength": {
        "abbr": "LEN",
        "system_message": "Answer with at least 300 words.",
        "conflict_suffix": "Answer with fewer than 50 words."
    },
    "json": {
        "abbr": "JSN",
        "system_message": "Respond in JSON format with keys 'answer' and 'reasoning'; output nothing else.",
        "conflict_suffix": "Respond in plain text prose, no JSON formatting."
    },
    "digits": {
        "abbr": "DIG",
        "system_message": "Your response must not contain any digits (0-9).",
        "conflict_suffix": "Your response must include at least three digits."
    },
    "list": {
        "abbr": "LST",
        "system_message": "Respond as a numbered list with exactly five items. Provide exactly five numbered items (1.-5.).",
        "conflict_suffix": "Respond as a single paragraph without any list formatting or line breaks."
    },
    "sentence": {
        "abbr": "SNT",
        "system_message": "Respond in exactly 10 sentences.",
        "conflict_suffix": "Respond fewer than five sentences."
    },
    "quotepresence": {
        "abbr": "QUO",
        "system_message": 'Include at least one quoted phrase wrapped in double quotes (" ").',
        "conflict_suffix": "Do not use any quotation marks in your answer."
    }
}

created_files = []

tasks_path = "/mnt/data/_temp_tasks.json"
if not os.path.exists(tasks_path):
    tasks = [
        "Describe the greenhouse effect and explain how human activities, such as fossil-fuel combustion, intensify this natural process.",
        "Explain quantum entanglement in accessible terms, then cite one landmark experiment that confirmed its non-classical correlations.",
        "Summarize the main political, economic, and social causes that led to World War I in a concise, chronological narrative.",
        "Provide a beginner-friendly introduction to machine learning and briefly contrast supervised with unsupervised learning.",
        "Explain how blockchain technology maintains a tamper-evident ledger and mention one real-world application beyond cryptocurrencies.",
        "Outline the three stages of cellular respiration, stating where each occurs in the cell and their approximate ATP yield.",
        "Describe the concept of supply and demand, and illustrate market equilibrium with a short numerical example.",
        "State Newton’s first law of motion and give one everyday scenario that clearly demonstrates inertia.",
        "Give a step-by-step recipe for classic pancakes, including batter preparation and proper griddle temperature.",
        "Discuss two major ways the Renaissance reshaped European culture, touching on art and scientific inquiry.",
        "Explain the historical significance of the Magna Carta and cite one modern democratic principle it helped inspire.",
        "Restate the law of conservation of energy and illustrate it with the operation of a simple pendulum.",
        "Describe the basic structure of the Internet and outline how data packets travel from sender to receiver.",
        "Provide five practical safety tips to follow during and immediately after an earthquake.",
        "Describe the eight principal phases of the Moon and explain why they appear in a 29-day cycle.",
        "Explain plate tectonics theory and relate it to the formation of earthquakes and mountain ranges.",
        "Write clear, numbered instructions for changing a bicycle tire on the roadside without specialized tools.",
        "Provide a brief history of jazz music, mentioning its roots in New Orleans and its evolution through bebop.",
        "Describe the main functions of the United Nations and reference a recent humanitarian or peacekeeping mission.",
        "Explain the basic principles of quantum computing and note one challenge that hinders large-scale deployment.",
        "Compare photosynthesis and chemosynthesis, highlighting their energy sources and typical ecosystems.",
        "Summarize the events and outcomes of the American Civil War in two concise paragraphs.",
        "Explain the process of DNA replication, naming the key enzymes involved.",
        "Describe how vaccines stimulate adaptive immunity and why booster shots are sometimes required.",
        "Provide step-by-step instructions for brewing pour-over coffee with flavor optimization tips.",
        "Explain the principle of relativity and give an everyday analogy to illustrate time dilation.",
        "Summarize the economic causes of the 2008 global financial crisis.",
        "Outline the lifecycle of a butterfly, mentioning each metamorphic stage and its duration.",
        "Describe the structure and function of the human mitochondrion in lay terms.",
        "Explain the greenhouse gas effect of methane compared with carbon dioxide.",
        "Provide guidelines for safe hiking in alpine environments, including preparation and emergency protocols.",
        "Discuss the primary objectives of the Kyoto Protocol and its impact on global emissions.",
        "Describe the major components of a computer CPU and their respective roles.",
        "Explain the concept of blockchain consensus and compare Proof-of-Work with Proof-of-Stake.",
        "Summarize the plot of Shakespeare’s Hamlet in a structured synopsis.",
        "Outline the scientific method, emphasizing hypothesis formulation and controlled experimentation.",
        "Describe the causes and effects of ocean acidification on marine life.",
        "Explain the Doppler effect and provide one practical application in astronomy.",
        "Provide a simple recipe for homemade guacamole with freshness preservation advice.",
        "Explain why the sky appears blue using Rayleigh scattering.",
        "Summarize the history of the Silk Road and its influence on cultural exchange.",
        "Describe how GPS satellites determine a receiver’s position using trilateration.",
        "Explain Pascal’s law and illustrate it with a hydraulic lift example.",
        "Provide effective techniques for memorizing new vocabulary in a foreign language.",
        "Describe the structure of DNA and the significance of complementary base pairing.",
        "Explain the causes of the Industrial Revolution and mention two key inventions.",
        "Provide an overview of renewable energy types, focusing on their advantages and limitations.",
        "Explain basic principles of ethics and contrast consequentialism with deontology.",
        "Summarize the life and major works of Leonardo da Vinci in chronological order.",
        "Describe the steps involved in project management from initiation to closure.",
        "Explain what climate models do and discuss one uncertainty they commonly face.",
        "Describe the ecosystem services provided by coral reefs such as the Great Barrier Reef.",
        "Explain the concept of opportunity cost and give a short financial example.",
        "Provide safety guidelines for laboratory handling of strong acids and bases.",
        "Describe how photosynthesis differs from cellular respiration in terms of energy flow.",
        "Explain the role of chlorophyll in light absorption and energy conversion.",
        "Outline the basic steps for planting tomato seedlings in a home garden.",
        "Summarize the impact of globalization on small local businesses.",
        "Explain genetic drift and how it differs from natural selection.",
        "Describe the importance of the ozone layer and the consequences of its depletion.",
        "Summarize Homer’s Odyssey focusing on Odysseus’s key challenges.",
        "Explain how volcanic eruptions influence global climate patterns.",
        "Describe how electric cars work, including battery management and regenerative braking.",
        "Provide an introduction to artificial intelligence and mention two practical applications.",
        "Explain the role of enzymes in biochemical reactions and why temperature affects their activity.",
        "Summarize the basic principles of quantum mechanics that differ from classical physics.",
        "Provide a step-by-step guide to creating a secure password and managing credentials.",
        "Explain the concept of inflation and how central banks attempt to control it.",
        "Describe the stages of human development according to Piaget’s theory.",
        "Outline the main causes and effects of desertification.",
        "Explain the Pythagorean theorem and illustrate it with a numeric example.",
        "Summarize the achievements of Marie Curie and her contributions to science.",
        "Describe cloud formation and the role of condensation nuclei.",
        "Explain chemosynthesis and identify one deep-sea organism that relies on it.",
        "Summarize the events of the Cold War in a timeline format.",
        "Describe the principle of electromagnetism and its use in electric motors.",
        "Explain Heisenberg’s uncertainty principle in simple language.",
        "Provide tips for improving sleep hygiene and reducing insomnia.",
        "Describe the process of fermentation in bread making.",
        "Explain how antibiotics work and why misuse leads to resistance.",
        "Provide a basic first aid guide for treating minor cuts and scrapes.",
        "Explain the separation of powers among the three branches of U.S. government.",
        "Describe the historical significance of the Human Genome Project.",
        "Summarize the events and outcomes of the French Revolution.",
        "Provide a brief overview of the International Space Station and its research goals.",
        "Explain the mechanics of a total solar eclipse.",
        "Describe the water treatment process from intake to distribution.",
        "Provide practical advice for reducing household energy consumption.",
        "Explain the role of photosystems I and II in the light reactions of photosynthesis.",
        "Describe the mental benefits of regular exercise.",
        "Summarize the main ideas of Einstein’s theory of general relativity.",
        "Provide instructions for safely disposing of electronic waste.",
        "Explain how solar panels convert sunlight into electrical energy.",
        "Describe the function of the human kidney and its role in homeostasis.",
        "Explain cryptocurrency mining and the concept of hash rate.",
        "Provide a guide to setting up two-factor authentication on a mobile device.",
        "Summarize the major contributions of Ada Lovelace to computing.",
        "Describe the causes and symptoms of high blood pressure.",
        "Explain the role of biodiversity in maintaining healthy ecosystems.",
        "Outline the process of natural selection using Darwin’s finches as an example.",
        "Provide a recipe for a simple vegetarian chili with substitution tips.",
        "Explain the operation of a simple pendulum and factors that affect its period.",
        "Describe the steps of the Krebs cycle and its significance in metabolism.",
        "Summarize the main functions of the United Nations Security Council.",
        "Explain the differences between weather and climate.",
        "Describe the benefits and challenges of remote work arrangements.",
        "Provide guidelines for composting kitchen waste effectively.",
        "Explain the concept of dark matter and evidence supporting its existence.",
        "Describe the life cycle of a star like our Sun.",
        "Summarize the objectives and outcomes of the Apollo 11 mission.",
        "Explain how machine learning differs from traditional rule-based programming.",
        "Provide steps to prepare a professional presentation slide deck.",
        "Describe the process by which rivers form deltas.",
        "Explain the basic operation of a transistor in digital circuits.",
        "Summarize the key nutrients required for plant growth.",
        "Provide safety advice for cyclists riding in urban traffic.",
        "Explain the greenhouse effect on Venus and implications for Earth.",
        "Describe the structure of bacterial cells and how antibiotics target them.",
        "Summarize the major discoveries of the Hubble Space Telescope.",
        "Provide a beginner’s guide to mindfulness meditation.",
        "Explain the physics of sound waves and how frequency relates to pitch.",
        "Describe the process of peer review in scientific publishing.",
        "Summarize the differences between renewable and non-renewable resources.",
        "Provide instructions for backing up important data on a personal computer.",
        "Explain the effects of deforestation on global carbon cycles.",
        "Describe the invention of the printing press and its impact on literacy.",
        "Summarize the stages of mitosis with emphasis on chromosome behavior.",
        "Explain the role of neurotransmitters in synaptic transmission.",
        "Provide a concise history of the Olympic Games from ancient Greece to modern times.",
        "Describe the process of desalination and its environmental considerations.",
        "Explain the concept of half-life and how it is used in radiometric dating.",
        "Provide tips for reducing plastic waste in daily life.",
        "Describe the causes and effects of soil erosion.",
        "Explain the role of the endocrine system in human physiology.",
        "Summarize the structure and functions of the European Union.",
        "Provide a step-by-step guide to basic CPR for adults.",
        "Explain the phenomenon of auroras and the role of solar wind.",
        "Describe the importance of wetlands in biodiversity conservation.",
        "Summarize the key features of the Linux operating system.",
        "Provide recommendations for responsible tourism in fragile ecosystems.",
        "Explain how tidal energy is harnessed to generate electricity.",
        "Describe the psychology behind confirmation bias with one real-world example.",
        "Summarize the process of protein synthesis from transcription to translation.",
        "Provide a recipe for baking whole-grain bread at home.",
        "Explain the concept of net neutrality and its relevance to internet users.",
        "Describe how vaccines are developed from preclinical research to approval.",
        "Summarize the causes and consequences of the Great Depression.",
        "Provide safety tips for working with household cleaning chemicals.",
        "Explain the mechanism of action of mRNA vaccines.",
        "Describe the role of the International Monetary Fund in global finance.",
        "Summarize the life cycle of a frog, including metamorphosis stages.",
        "Provide guidelines for ethical use of artificial intelligence.",
        "Explain the process of photosynthesis in algae, highlighting ecological importance.",
        "Describe the key principles of ergonomics in workplace design.",
        "Summarize the theory of evolution by natural selection in two sentences.",
        "Provide an overview of cloud computing service models: IaaS, PaaS, SaaS.",
        "Explain the function of red blood cells and hemoglobin.",
        "Describe the basic steps to create a budget for personal finances.",
        "Summarize the history and cultural significance of tea in China.",
        "Provide instructions for performing a simple science experiment on capillary action.",
        "Explain the greenhouse effect on Mars and why it is weaker than on Earth.",
        "Describe the contribution of Nikola Tesla to electric power systems.",
        "Summarize the importance of pollinators in agriculture.",
        "Provide tips for reducing screen time and mitigating digital eye strain.",
        "Explain how seismographs measure earthquake magnitude.",
        "Describe the effects of caffeine on the central nervous system.",
        "Summarize the main teachings of Buddhism in lay language.",
        "Provide a basic overview of wind turbine operation.",
        "Explain the difference between correlation and causation with a brief example.",
        "Describe how a bill becomes law in the United States Congress.",
        "Summarize the achievements of the Voyager missions.",
        "Provide guidelines for responsible social media usage to maintain privacy.",
        "Explain how CRISPR technology enables gene editing.",
        "Describe the process of photosynthesis under waterlogged conditions in rice.",
        "Summarize the steps of the water cycle with emphasis on evaporation and precipitation.",
        "Provide a brief introduction to the nervous system divisions: CNS and PNS.",
        "Explain the principles of the Scrum framework in project management.",
        "Describe how 3D printing works and its applications in medicine.",
        "Summarize the causes of antibiotic resistance and ways to combat it.",
        "Provide a recipe for a healthy smoothie rich in antioxidants.",
        "Explain the greenhouse effect of nitrous oxide compared to CO₂.",
        "Describe the function of stomata in plant leaves.",
        "Summarize the importance of data encryption in cybersecurity.",
        "Provide steps to set up a simple home wireless network securely.",
        "Explain the Coanda effect and its role in aircraft lift.",
        "Describe the process of making yogurt through bacterial fermentation.",
        "Summarize the major plot points of George Orwell’s 1984.",
        "Provide safety measures for using power tools at home.",
        "Explain the basic working principle of a lithium-ion battery.",
        "Describe how to create a simple compost bin on a balcony.",
        "Summarize the benefits and drawbacks of nuclear power.",
        "Provide practical steps for conserving water in daily household activities.",
        "Explain the role of the World Health Organization during a pandemic.",
        "Describe the phenomenon of red tides and their ecological impacts.",
        "Summarize the key elements of the Paris Agreement on climate change.",
        "Provide guidelines for writing an effective cover letter for job applications.",
        "Explain the principle of operation of a drone’s quadcopter design.",
        "Describe the process of photosynthesis in cacti adapted to arid conditions.",
        "Summarize the significance of the discovery of penicillin.",
        "Provide tips for preventing phishing attacks in email communication.",
        "Explain the Fibonacci sequence and its appearance in nature.",
        "Describe the causes and prevention of cyberbullying among teenagers.",
        "Summarize the function of chloroplasts and their origin via endosymbiosis.",
        "Provide instructions for performing a basic home energy audit.",
        "Explain how phase-change materials store thermal energy.",
        "Describe the history and technology of the steam locomotive.",
        "Summarize the ethical considerations of autonomous vehicles.",
        "Provide a beginner’s guide to setting up a vegetable garden on a balcony.",
        "Explain the Bernoulli principle and its application in airplane wings.",
        "Describe different methods of water desalination: reverse osmosis and distillation.",
        "Summarize the Nobel Prize selection process.",
        "Provide guidelines for reducing carbon footprint while traveling.",
        "Explain the difference between AC and DC electrical current.",
        "Describe the process of cheese making from milk to aging.",
        "Summarize the contributions of Rosalind Franklin to DNA structure discovery.",
        "Provide steps for effective public speaking preparation.",
        "Explain the concept of smart grids in modern electricity distribution.",
        "Describe how weather forecasting models assimilate data from satellites.",
        "Summarize the importance of wetlands for flood mitigation.",
        "Provide a short history of space telescopes leading up to the James Webb Space Telescope."
    ]

else:
    tasks = json.load(open(tasks_path))

# Generate permuted datasets
for type_name, cfg in type_configs.items():
    records = []
    for idx, task in enumerate(tasks, 1):
        id_idx = f"{idx:03d}"
        # normal sample unchanged
        records.append({
            "id": f"{cfg['abbr']}_{id_idx}_normal",
            "system_message": cfg["system_message"],
            "user_message": task,
            "label": "normal"
        })
        # conflict sample with swapped constraints
        records.append({
            "id": f"{cfg['abbr']}_{id_idx}_conflict",
            "system_message": cfg["conflict_suffix"],  # swapped
            "user_message": f"{task} {cfg['system_message']}",  # append original system constraint
            "label": "conflict"
        })
    perm_file = os.path.join(base_path, f"permutation_{type_name}_instruction.json")
    with open(perm_file, "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
    created_files.append(perm_file)

created_files
